[keyboard]
name = "rmk-lily58"
product_name = "rmk-lily58"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "rmk"
chip = "nrf52840"

[layout]
rows = 5
cols = 12
layers = 3
keymap = [
    # Base layer
    [
        ["Escape", "Kc1", "Kc2", "Kc3", "Kc4", "Kc5", "Kc6", "Kc7", "Kc8", "Kc9", "Kc0", "Grave"],
        ["Tab", "Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P", "Minus"],
        ["LCtrl", "A", "S", "D", "F", "G", "H", "J", "K", "L", "Semicolon", "Quote"],
        ["LShift", "Z", "X", "C", "V", "B", "N", "M", "Comma", "Dot", "Slash", "RShift"],
        ["__", "LAlt", "LGui", "MO(1)", "Space", "LeftBracket", "RightBracket", "Enter", "MO(2)", "Backspace", "RGui", "__"],
    ],
    # Lower layer
    [
        ["__", "__", "__", "__", "__", "__", "__", "__", "__", "__", "__", "__"],
        ["F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "F10", "F11", "F12"],
        ["Grave", "SHIFTED(Kc1)", "SHIFTED(Kc2)", "SHIFTED(Kc3)", "SHIFTED(Kc4)", "SHIFTED(Kc5)", "SHIFTED(Kc6)", "SHIFTED(Kc7)", "SHIFTED(Kc8)", "SHIFTED(Kc9)", "SHIFTED(Kc0)", "SHIFTED(Grave)"],
        ["__", "__", "__", "__", "__", "__", "__", "Minus", "KpPlus", "LeftBracket", "RightBracket", "SHIFTED(Backslash)"],
        ["__", "__", "__", "__", "__", "__", "__", "__", "__", "__", "__", "__"],
    ],
    # Raise layer
    [
        ["__", "BrightnessDown", "BrightnessUp", "AudioMute", "AudioVolDown", "AudioVolUp", "MediaPrevTrack", "MediaPlayPause", "MediaNextTrack", "__", "__", "__"],
        ["Grave", "Kc1", "Kc2", "Kc3", "Kc4", "Kc5", "Kc6", "Kc7", "Kc8", "Kc9", "Kc0", "__"],
        ["F1", "F2", "F3", "F4", "F5", "F6", "Left", "Down", "UP", "Right", "__", "__"],
        ["F7", "F8", "F9", "F10", "F11", "F12", "KpPlus", "Minus", "Equal", "LeftBracket", "RightBracket", "Backslash"],
        ["__", "__", "__", "__", "__", "__", "__", "__", "__", "__", "__", "__"],
    ],
]

[ble]
enabled = true

[split]
connection = "ble"

[split.central]
rows = 5
cols = 6
row_offset = 0
col_offset = 0
ble_addr = [0x18, 0xe2, 0x21, 0x80, 0xc0, 0xc7]

[split.central.matrix]
input_pins = [
    "P0_24",
    "P1_00",
    "P0_11",
    "P1_04",
    "P1_06",
]
output_pins = [
    "P0_02",
    "P1_15",
    "P1_13",
    "P1_11",
    "P0_10",
    "P0_09",
]

[[split.peripheral]]
rows = 5
cols = 6
row_offset = 0
col_offset = 6
ble_addr = [0x7e, 0xfe, 0x73, 0x9e, 0x66, 0xe3]

[split.peripheral.matrix]
input_pins = [
    "P0_24",
    "P1_00",
    "P0_11",
    "P1_04",
    "P1_06",
]
output_pins = [
    "P0_09",
    "P0_10",
    "P1_11",
    "P1_13",
    "P1_15",
    "P0_02",
]
